### ISSUE TITLE
registerOnSharedPreferenceChangeListener无效

### ISSUE THREAD

**Issue by gdpancheng** [limpoxe/Android-Plugin-Framework#17]
在插件中怎么监听 主程序中的registerOnSharedPreferenceChangeListener

**Comment by gdpancheng** [comment]
怎么样让插件中监听registerOnSharedPreferenceChangeListener 的时候 主程序中插入一条sharedpreference 插件可以得到监听消息

**Comment by limpoxe** [comment]
@gdpancheng 这个问题和插件没关系。跨进程了。插件和宿主不在同一个进程里面呀，怎么可能监听得到。。你要做这种监听就得把插件进程配置去掉。
