### ISSUE TITLE
为什么不强化对第三方APP的支持呢，这个才是目前插件领域的真正瓶颈点呢

### ISSUE THREAD

**Issue by greplay** [limpoxe/Android-Plugin-Framework#20]
基于约束的插件都已经被搞的遍地开花了，基于插件技术构建一个真正的能托管第三方APP的虚拟空间才是目前的瓶颈呢

**Comment by shaobin0604** [comment]
@gforetell 请问什么是“基于约束的插件”？

> 基于约束的插件都已经被搞的遍地开花了，基于插件技术构建一个真正的能托管第三方APP的虚拟空间才是目前的瓶颈呢

**Comment by nancyyihao** [comment]
@greplay LBE双开大师已经实现，不过没开源

**Comment by limpoxe** [comment]
完全托管的虚拟空间不适用于企业应用。

**Comment by shaobin0604** [comment]
@nancyyihao 可以看看 asLody 的 VirtualApp
