### ISSUE TITLE
宿主如何使用startActivityForResult从插件中获取数据

### ISSUE THREAD

**Issue by zhengdianfang** [limpoxe/Android-Plugin-Framework#21]
在宿主中使用 startActivityForResult 启动插件的Activity，从插件回到宿主时，无法回调宿主的onActivityResult方法，

是否现在还不支持，我用的是独立插件，求使用方法。

**Comment by limpoxe** [comment]
支持。无特殊用法，正常使用即可。

startActivityForResult这个方法本身有它自己的限制：不支持SingleTask，requestCode不支持负数，不支持ACTION_MAIN，不支持ACTION_VIEW。请仔细阅读API文档。
