### ISSUE TITLE
宿主Activity中加载Plugin类的问题

### ISSUE THREAD

**Issue by goatatop** [limpoxe/Android-Plugin-Framework#26]
如果Plugin类中需要Activity类型的Context，PluginContextTheme强转会发生异常，求助博主~

**Comment by limpoxe** [comment]
@hjw541988478 调用代码贴出来看下。可以试试PluginContextTheme.getOuter() 这个方法返回组件附着的Activity对象

**Comment by goatatop** [comment]
现在遇到的问题是：A,B,C三个APK，在加载完成后，去启动B或者C，会发生ClassNotFoundException的错误（B依赖A，C依赖B也依赖A，已经在B和C中使用provided去掉重复打包），有什么可能会导致这种异常么= =

**Comment by limpoxe** [comment]
没有在manifest中配依赖关系，所以框架不知道它们之间的依赖关系

**Comment by goatatop** [comment]
Good ~ 我先试试后续有更多问题的话麻烦了 ~

**Comment by goatatop** [comment]
现在遇到的问题是插件Activity setContentView(layResID) 后 ，findViewById()拿到的View是 null 。。

**Comment by goatatop** [comment]
`W/ResourceType(92197): ResTable_typeSpec entry count inconsistent: given 104, previously 76
W/ResourceType(92197): ResTable_typeSpec entry count inconsistent: given 46, previously 1
W/ResourceType(92197): ResTable_typeSpec entry count inconsistent: given 1, previously 39
W/ResourceType(92197): ResTable_typeSpec entry count inconsistent: given 2, previously 10
W/ResourceType(92197): ResTable_typeSpec entry count inconsistent: given 321, previously 21
W/ResourceType(92197): ResTable_typeSpec entry count inconsistent: given 14, previously 8
W/ResourceType(92197): ResTable_typeSpec entry count inconsistent: given 240, previously 75
W/ResourceType(92197): ResTable_typeSpec entry count inconsistent: given 19, previously 318
W/ResourceType(92197): ResTable_typeSpec entry count inconsistent: given 6, previously 5`
感觉是固定资源ID造成的错误，Build的时候会有相关的警告

**Comment by goatatop** [comment]
已经解决了
