### ISSUE TITLE
从宿主获取Plugin的Context

### ISSUE THREAD

**Issue by goatatop** [limpoxe/Android-Plugin-Framework#28]
从宿主获取Plugin的Context有什么好的方法可以获取么？

**Comment by goatatop** [comment]
非宿主进程没办法拿到呀==

**Comment by limpoxe** [comment]
什么是“非宿主进程”？
PluginContext只在插件进程存在，主进程不能获取，跨进程了。
而且宿主不应该尝试获取插件Context。

你非得这么做，就得把插件进程和宿主进程配置为同一进程。
方法看ReadMe
