### ISSUE TITLE
PluginContextTheme.getOuter无法获取Activity类型的Context

### ISSUE THREAD

**Issue by goatatop** [limpoxe/Android-Plugin-Framework#29]
实际上获取的是配置在宿主的Application类型的Context

**Comment by limpoxe** [comment]
这取决于你的运行时容器是什么。如果Fragment自身或者插件控件View自生，则Outer是Application。
如果是它们附着的Activity，则返回Activity

**Comment by goatatop** [comment]
其实我只是取插件里面的View运行在宿主Activity，所以才这样
