### ISSUE TITLE
不知道为什么现在已经找不到openAtlasExtention了

### ISSUE THREAD

**Issue by andrewlu1** [limpoxe/Android-Plugin-Framework#31]
openAtlasExtention 完全搜不到资料了，我只想用用定制的aapt呀。。。

**Comment by limpoxe** [comment]
原作者（https://github.com/bunnyblue）改过项目名字，叫ACDD，
如果还找不到的话可以去携程（https://github.com/CtripMobile/DynamicAPK）的找找，一样的。
