### ISSUE TITLE
最近碰到activity跳转后但界面不更新的问题

### ISSUE THREAD

**Issue by qiaoqileng** [limpoxe/Android-Plugin-Framework#32]
卡点的手机常见，如华为P7，看logcat可以发现点击事件有触发，而界面还是前一个页面

**Comment by limpoxe** [comment]
@qiaoqileng  有可疑log吗

**Comment by qiaoqileng** [comment]
已经被我们老大解决了，是因为一个基类activity里有用动画资源，别的手机没啥影响，部分手机就出现上述问题，还是谢谢
