### ISSUE TITLE
Crash when open weex app as plugin

### ISSUE THREAD

**Issue by Chris85bh** [limpoxe/Android-Plugin-Framework#47]
Hi , I developed an app and use Weex (A framework for building Mobile cross-platform UI by Aliibaba), generate an apk as a plugin, can install  successfully, but it crashed when click to open.

**Comment by limpoxe** [comment]
Please send me the Weex apk。mail：fixerror@163.com

**Comment by Chris85bh** [comment]
Hi, had sent you.

**Comment by limpoxe** [comment]
I haven't received yet.

**Comment by Chris85bh** [comment]
Resend. You can check the junk mail box maybe.

**Comment by limpoxe** [comment]
Not received. You can commit to your git repository or send pull request to my  repository

**Comment by Chris85bh** [comment]
Hi, I changed  gradle configuration, and now it's OK, so that's not an APF issue. Closed, Thanks anyway.
