### ISSUE TITLE
WaitForLoadingPluginActivity NPE

### ISSUE THREAD

**Issue by jason0539** [limpoxe/Android-Plugin-Framework#48]
java.lang.NullPointerException

Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.res.Resources.newTheme()' on a null object reference
com.limpoxe.fairy.core.d.c(PluginContextTheme.java:140)
com.limpoxe.fairy.core.d.setTheme(PluginContextTheme.java:99)
com.limpoxe.fairy.core.PluginLauncher.startPlugin(PluginLauncher.java:121)
com.limpoxe.fairy.core.loading.WaitForLoadingPluginActivity$1.run(WaitForLoadingPluginActivity.java:72)
java.lang.Thread.run(Thread.java:818)

出现该问题的都是OPPO机器

**Comment by limpoxe** [comment]
原因看起来是插件res创建失败，检查log，看下PluginLauncher这个类第99行log是否有打印

**Comment by jason0539** [comment]
日志都是线上统计到的，找了对应机型没有复现这个问题
