### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by demoface** [limpoxe/Android-Plugin-Framework#56]
我写了个测试工程，然后把apk包放进去发现提示MainActivity找不到类。我把你的sample里面的helloworld放到独立工程中打包放到assert里面，提示Applicaiton找不到

**Comment by demoface** [comment]
三星，6.0

**Comment by limpoxe** [comment]
先试下Samples/PluginMain/PluginMain-universal-debug.apk这个apk是否有问题。

**Comment by demoface** [comment]
不好意思，找到问题了，我发现我开了instant run，点击导航栏运行的时候在app/build/output/里面生成的app-debug里面没有我的代码，我关掉就可以了
