### ISSUE TITLE
startActivity

### ISSUE THREAD

**Issue by demoface** [limpoxe/Android-Plugin-Framework#57]
在Fragment里面startActivity会提示没有在manifest里面注册，需要getActivity().startActivity

**Comment by limpoxe** [comment]
Fragment.startActivity等同于Fragment.getContext.startActivity。
而Fragment.getContext 和 Fragment.getActivity返回的应该是同一个对象，就是其所在的Activity。
Debug看一下你的getContext返回的是什么。
