### ISSUE TITLE
在android studio3.2上host.gradle报错

### ISSUE THREAD

**Issue by pengbs** [limpoxe/Android-Plugin-Framework#74]
No signature of method: com.android.build.gradle.internal.scope.VariantScopeImpl.getMergeResourcesTask() is applicable for argument types: () values: []

**Comment by wangben5** [comment]
请问你解决了吗?我也遇到这个问题了

**Comment by limpoxe** [comment]
参考一下demo的gradle版本和android gradle plugin版本

**Comment by pengbs** [comment]
gradle版本使用3.0.1就行了
