### ISSUE TITLE
请问，如何catach到插件的crash，使其不影响宿主？

### ISSUE THREAD

**Issue by pengbs** [limpoxe/Android-Plugin-Framework#75]
您好，经测试我发现独立插件如果运行出现crash了，宿主也会跟着crash，请问有什么办法能让宿主不受影响吗？

**Comment by limpoxe** [comment]
进程隔离。默认是进程隔离的，你是不是放开了

**Comment by pengbs** [comment]
没有，我发现第一次插件crash了不会影响宿主，但是如果这时候再次点击打开插件，就会黑屏卡死

**Comment by limpoxe** [comment]
哪个版本？

**Comment by pengbs** [comment]
0.0.65-snapshot

**Comment by limpoxe** [comment]
在卡死的时候dump一下线程看看。可能是死锁或者递归了
