### ISSUE TITLE
最新版本报Cannot run program "aapt2": CreateProcess error=2

### ISSUE THREAD

**Issue by pengbs** [limpoxe/Android-Plugin-Framework#76]
希望作者帮帮忙，集成最新0.0.67会报Cannot run program "aapt2": CreateProcess error=2，一直编译不过

**Comment by limpoxe** [comment]
在命令行执行一下aapt2，如果执行不了，需要在环境变量中配置下。
另外请检查下这几个配置
android.enableAapt2=true
com.android.tools.build:gradle:3.2.1，
gradle-4.6
buildToolsVersion>28.0.3
如果是windows系统，检查一下脚本中的文件分隔符
