### ISSUE TITLE
master分支Demo无法运行

### ISSUE THREAD

**Issue by yangyonguo** [limpoxe/Android-Plugin-Framework#9]
运行环境：HUAWEI PE-TL10，Android 6.0，API 23
错误日志：
03-23 14:34:37.838 26962-26975/com.example.pluginmain E/HAL: load: id=gralloc != hmi->id=gralloc
03-23 14:34:38.039 26989-27002/com.example.pluginmain:plugin E/HAL: load: id=gralloc != hmi->id=gralloc
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115] JNI ERROR (app bug): local reference table overflow (max=512)
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115] local reference table dump:
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]   Last 10 entries (of 512):
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       511: 0x1304e740 java.lang.Object[](4 elements)
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       510: 0x1306c250 java.lang.reflect.Method
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       509: 0x12e092e0 java.lang.String "com.plugin.core.... (45 chars)
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       508: 0x12cc7ce0 android.app.ActivityThread$ApplicationThread
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       507: 0x12d864a0 $Proxy3
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       506: 0x12d864a0 $Proxy3
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       505: 0x12f4d0a0 java.lang.Object[](3 elements)
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       504: 0x12f4e9a0 java.lang.reflect.Method
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       503: 0x1306b840 java.lang.String "com.example.plug... (22 chars)
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       502: 0x12dfd7e0 $Proxy5
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]   Summary:
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         2 of $Proxy3 (1 unique instances)
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       200 of $Proxy5 (1 unique instances)
03-23 14:34:38.636 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       100 of java.lang.Object[](3 elements) (100 unique instances)
03-23 14:34:38.637 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         1 of java.lang.Object[](4 elements)
03-23 14:34:38.637 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         2 of java.lang.Class (2 unique instances)
03-23 14:34:38.637 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         1 of java.lang.String[](3 elements)
03-23 14:34:38.637 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       104 of java.lang.String (104 unique instances)
03-23 14:34:38.637 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       101 of java.lang.reflect.Method (101 unique instances)
03-23 14:34:38.637 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.app.ActivityThread$ApplicationThread
03-23 14:34:38.637 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115] 
03-23 14:34:38.637 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/runtime.cc:368] Runtime aborting...
03-23 14:34:38.637 26989-26989/com.example.pluginmain:plugin A/art: art/runtime/runtime.cc:368] 
03-23 14:34:38.637 26989-26989/com.example.pluginmain:plugin A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 26989 (uginmain:plugin)
03-23 14:34:39.219 27029-27042/com.example.pluginmain:plugin E/HAL: load: id=gralloc != hmi->id=gralloc
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115] JNI ERROR (app bug): local reference table overflow (max=512)
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115] local reference table dump:
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]   Last 10 entries (of 512):
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       511: 0x12ec5bc0 java.lang.Object[](4 elements)
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       510: 0x12efbac0 java.lang.reflect.Method
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       509: 0x12e0a350 java.lang.String "com.plugin.core.... (45 chars)
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       508: 0x12cca0c0 android.app.ActivityThread$ApplicationThread
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       507: 0x12d86530 $Proxy3
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       506: 0x12d86530 $Proxy3
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       505: 0x12e43560 java.lang.Object[](3 elements)
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       504: 0x12e602e0 java.lang.reflect.Method
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       503: 0x12e8bac0 java.lang.String "com.example.plug... (22 chars)
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       502: 0x12dfd870 $Proxy5
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]   Summary:
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         2 of $Proxy3 (1 unique instances)
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       200 of $Proxy5 (1 unique instances)
03-23 14:34:39.903 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       100 of java.lang.Object[](3 elements) (100 unique instances)
03-23 14:34:39.904 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         1 of java.lang.Object[](4 elements)
03-23 14:34:39.904 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         2 of java.lang.Class (2 unique instances)
03-23 14:34:39.904 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         1 of java.lang.String[](3 elements)
03-23 14:34:39.904 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       104 of java.lang.String (104 unique instances)
03-23 14:34:39.904 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       101 of java.lang.reflect.Method (101 unique instances)
03-23 14:34:39.904 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.app.ActivityThread$ApplicationThread
03-23 14:34:39.904 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115] 
03-23 14:34:39.904 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/runtime.cc:368] Runtime aborting...
03-23 14:34:39.904 27029-27029/com.example.pluginmain:plugin A/art: art/runtime/runtime.cc:368] 
03-23 14:34:39.904 27029-27029/com.example.pluginmain:plugin A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 27029 (uginmain:plugin)
03-23 14:34:40.628 27072-27104/com.example.pluginmain:plugin E/HAL: load: id=gralloc != hmi->id=gralloc
03-23 14:34:40.646 27086-27105/com.example.pluginmain E/HAL: load: id=gralloc != hmi->id=gralloc
03-23 14:34:41.313 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115] JNI ERROR (app bug): local reference table overflow (max=512)
03-23 14:34:41.313 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115] local reference table dump:
03-23 14:34:41.313 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]   Last 10 entries (of 512):
03-23 14:34:41.313 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       511: 0x13019160 java.lang.Object[](4 elements)
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       510: 0x1301a370 java.lang.reflect.Method
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       509: 0x12e0b350 java.lang.String "com.plugin.core.... (45 chars)
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       508: 0x12cca8e0 android.app.ActivityThread$ApplicationThread
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       507: 0x12d885c0 $Proxy3
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       506: 0x12d885c0 $Proxy3
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       505: 0x12f06a40 java.lang.Object[](3 elements)
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       504: 0x12f0ea60 java.lang.reflect.Method
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       503: 0x13030500 java.lang.String "com.example.plug... (22 chars)
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       502: 0x12dfe900 $Proxy5
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]   Summary:
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         2 of $Proxy3 (1 unique instances)
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       200 of $Proxy5 (1 unique instances)
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       100 of java.lang.Object[](3 elements) (100 unique instances)
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         1 of java.lang.Object[](4 elements)
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         2 of java.lang.Class (2 unique instances)
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         1 of java.lang.String[](3 elements)
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       104 of java.lang.String (104 unique instances)
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       101 of java.lang.reflect.Method (101 unique instances)
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.app.ActivityThread$ApplicationThread
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115] 
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/runtime.cc:368] Runtime aborting...
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/art: art/runtime/runtime.cc:368] 
03-23 14:34:41.314 27072-27072/com.example.pluginmain:plugin A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 27072 (uginmain:plugin)
03-23 14:34:42.007 27147-27177/com.example.pluginmain:plugin E/HAL: load: id=gralloc != hmi->id=gralloc
03-23 14:34:42.091 27163-27179/com.example.pluginmain E/HAL: load: id=gralloc != hmi->id=gralloc
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115] JNI ERROR (app bug): local reference table overflow (max=512)
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115] local reference table dump:
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]   Last 10 entries (of 512):
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       511: 0x1314bd80 java.lang.Object[](4 elements)
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       510: 0x13139610 java.lang.reflect.Method
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       509: 0x12e0d3c0 java.lang.String "com.plugin.core.... (45 chars)
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       508: 0x12cdb0c0 android.app.ActivityThread$ApplicationThread
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       507: 0x12d8d6e0 $Proxy3
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       506: 0x12d8d6e0 $Proxy3
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       505: 0x130186a0 java.lang.Object[](3 elements)
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       504: 0x12ffed60 java.lang.reflect.Method
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       503: 0x132ea040 java.lang.String "com.example.plug... (22 chars)
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       502: 0x12dfda20 $Proxy5
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]   Summary:
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         2 of $Proxy3 (1 unique instances)
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       200 of $Proxy5 (1 unique instances)
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       100 of java.lang.Object[](3 elements) (100 unique instances)
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         1 of java.lang.Object[](4 elements)
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         2 of java.lang.Class (2 unique instances)
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         1 of java.lang.String[](3 elements)
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       104 of java.lang.String (104 unique instances)
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       101 of java.lang.reflect.Method (101 unique instances)
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.app.ActivityThread$ApplicationThread
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115] 
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/runtime.cc:368] Runtime aborting...
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/art: art/runtime/runtime.cc:368] 
03-23 14:34:42.696 27147-27147/com.example.pluginmain:plugin A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 27147 (uginmain:plugin)
03-23 14:34:43.432 27223-27238/com.example.pluginmain:plugin E/HAL: load: id=gralloc != hmi->id=gralloc
03-23 14:34:44.098 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115] JNI ERROR (app bug): local reference table overflow (max=512)
03-23 14:34:44.098 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115] local reference table dump:
03-23 14:34:44.098 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]   Last 10 entries (of 512):
03-23 14:34:44.098 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       511: 0x1301c3c0 java.lang.Object[](4 elements)
03-23 14:34:44.098 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       510: 0x13034f10 java.lang.reflect.Method
03-23 14:34:44.098 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       509: 0x12dd3430 java.lang.String "com.plugin.core.... (45 chars)
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       508: 0x12cd8ce0 android.app.ActivityThread$ApplicationThread
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       507: 0x12d8f800 $Proxy3
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       506: 0x12d8f800 $Proxy3
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       505: 0x12f3cda0 java.lang.Object[](3 elements)
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       504: 0x12f4b6a0 java.lang.reflect.Method
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       503: 0x12ff0f00 java.lang.String "com.example.plug... (22 chars)
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       502: 0x12dffb40 $Proxy5
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]   Summary:
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         2 of $Proxy3 (1 unique instances)
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       200 of $Proxy5 (1 unique instances)
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       100 of java.lang.Object[](3 elements) (100 unique instances)
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         1 of java.lang.Object[](4 elements)
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         2 of java.lang.Class (2 unique instances)
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         1 of java.lang.String[](3 elements)
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       104 of java.lang.String (104 unique instances)
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]       101 of java.lang.reflect.Method (101 unique instances)
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115]         1 of android.app.ActivityThread$ApplicationThread
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/indirect_reference_table.cc:115] 
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/runtime.cc:368] Runtime aborting...
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/art: art/runtime/runtime.cc:368] 
03-23 14:34:44.099 27223-27223/com.example.pluginmain:plugin A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 27223 (uginmain:plugin)

**Comment by yangyonguo** [comment]
直接安装PluginMain里面的APK也是相同的错误

**Comment by limpoxe** [comment]
Fixed Thanks
