### ISSUE TITLE
插件无法使用显示在应用上层特性

### ISSUE THREAD

**Issue by Saint-Theana** [limpoxe/Android-Plugin-Framework#96]
当插件里使用了Dialog并且添加了WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY 特征后抛出异常
android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@cfe1696 -- permission denied for window type 2038

代码如下
   final AlertDialog dialog = builder.create();
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                dialog.getWindow().setType(
                        WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY);
            } else {
                dialog.getWindow().setType(WindowManager.LayoutParams.TYPE_PHONE);
            }
            dialog.setCanceledOnTouchOutside(false);
            dialog.show();

异常部分
android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@cfe1696 -- permission denied for window type 2038
at android.view.ViewRootImpl.setView(ViewRootImpl.java:952)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
	at android.app.Dialog.show(Dialog.java:342)
        at com.myandroidplugin.template$7.onMenuItemClick(TestDialogActivity.java:372)

安卓版本: 10

宿主确定拥有可以弹出显示在其他app上层的权限。

研究了好几个小时，翻了不少安卓源码，奈何水平有限。望大佬能够解决。

此外提个小建议。
已知本项目插件分独立插件和非独立插件。
独立插件无法使用宿主中的类。
非独立插件的开发又需要引入完整的宿主的基线包，在某些情况下不适用，比如开放sdk给第三方人员开发的情况。
在非独立插件开发中如果混淆mapping对不上宿主的那基本上会炸。如果将混淆mapping提供出来那就意味着宿主混淆就单纯只有体积缩减，某种意义上就像是裸奔。

所以是否可以提供一个折中的方案。混合模式。
插件的PluginClassLoader和RealPluginClassLoader中重写loadClass方法。由原来的爹妈委派模式改为自力更生模式。
插件的ClassLoader传入dex路径，并且先尝试自己找Class，找不到再找爹妈。
参考:
	@Override
	protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
		Class<?> c = findLoadedClass(name);
		if(c==null){
			try {
				c = findClass(name);
			}catch (ClassNotFoundException e){
//			ignore
				LogUtil.printException("class not found by self.",e);
			}
			if(c==null){
				if(parent!=null){
					c=parent.loadClass(name);
				}
			}
		}
		return c;
	}
水平有限，还望见谅

**Comment by limpoxe** [comment]
第一个问题我看下。
第二个问题，没太看懂。是指希望第三方能为宿主开发插件，且插件需要调用宿主的功能，但又不希望将宿主基线包开放出去是吗

**Comment by limpoxe** [comment]
关于第一个问题的解决方法：
WindowManager.LayoutParams windowParams = new WindowManager.LayoutParams();
windowParams.packageName = <<宿主包名>>;

**Comment by Saint-Theana** [comment]
> 第一个问题我看下。 第二个问题，没太看懂。是指希望第三方能为宿主开发插件，且插件需要调用宿主的功能，但又不希望将宿主基线包开放出去是吗

差不多就是这个意思吧，总之只是提一个意见，也许有这个需求的人并不多。
